[2025-06-01T10:02:22.464+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2020-04-09T00:00:00+00:00 [queued]>
[2025-06-01T10:02:22.475+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_dag.save_data_task scheduled__2020-04-09T00:00:00+00:00 [queued]>
[2025-06-01T10:02:22.475+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-06-01T10:02:22.557+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): save_data_task> on 2020-04-09 00:00:00+00:00
[2025-06-01T10:02:22.565+0000] {standard_task_runner.py:57} INFO - Started process 8292 to run task
[2025-06-01T10:02:22.572+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'second_dag', 'save_data_task', 'scheduled__2020-04-09T00:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmpc1zwfqnm']
[2025-06-01T10:02:22.575+0000] {standard_task_runner.py:85} INFO - Job 411: Subtask save_data_task
[2025-06-01T10:02:22.693+0000] {task_command.py:410} INFO - Running <TaskInstance: second_dag.save_data_task scheduled__2020-04-09T00:00:00+00:00 [running]> on host 27c4b93144a0
[2025-06-01T10:02:23.100+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_dag' AIRFLOW_CTX_TASK_ID='save_data_task' AIRFLOW_CTX_EXECUTION_DATE='2020-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-04-09T00:00:00+00:00'
[2025-06-01T10:02:23.163+0000] {my_second_dag.py:49} INFO - Fetching value USD: None
[2025-06-01T10:02:23.177+0000] {base.py:73} INFO - Using connection ID 'pg_database' for task execution.
[2025-06-01T10:02:23.179+0000] {my_second_dag.py:58} INFO - Connection: postgresql://***:***@***-postgres:5432/***
[2025-06-01T10:02:23.179+0000] {logging_mixin.py:150} INFO - Data saved successfully.
[2025-06-01T10:02:23.180+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-06-01T10:02:23.209+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=second_dag, task_id=save_data_task, execution_date=20200409T000000, start_date=20250601T100222, end_date=20250601T100223
[2025-06-01T10:02:23.270+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-06-01T10:02:23.295+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
